"""followers

Revision ID: 1516f2bf68e0
Revises: 98239de59974
Create Date: 2020-05-02 16:41:20.003531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1516f2bf68e0'
down_revision = '98239de59974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
