"""user tokens

Revision ID: 166f1e4ac991
Revises: c04fd93f0c14
Create Date: 2020-07-13 17:12:12.024704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166f1e4ac991'
down_revision = 'c04fd93f0c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
