"""new fields in user model

Revision ID: 98239de59974
Revises: 86329aa561b6
Create Date: 2020-04-25 21:27:58.683857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98239de59974'
down_revision = '86329aa561b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
